### ISSUE TITLE
How can i connect with you

### ISSUE THREAD

**Issue by it5meyash** [shlyang/go2_nav#1]
I want to use hesai xt16 lidar on my go2. Facing some problems can you please help me.

**Comment by shlyang** [comment]
I would suggest starting from [Unitree's official code](https://support.unitree.com/home/zh/developer/SLAM%20and%20Navigation_service). 
After installation, you can launch Hesai Lidar's rosnode with the code below
```
source /unitree/module/graph_pid_ws/install/setup.bash
ros2 launch hesai_lidar hesai_lidar_launch.py
```
For some reason, I have to turn this repo into private.
My email address is yangsl737@gmail.com, feel free to reach out anytime for more discussions.
